### ISSUE TITLE
Unable to connect from Digital Ocean

### ISSUE THREAD

**Issue by arjunrao87** [arjunrao87/world-countries#7]
Not able to use Playground running on Digital Ocean
```
rror: getaddrinfo ENOTFOUND restcountries.eu restcountries.eu:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
Error: getaddrinfo ENOTFOUND restcountries.eu restcountries.eu:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

**Comment by arjunrao87** [comment]
Turns out this is not a digital ocean issue. The error is seen when the underlying REST service isnt available. Just retry after some time
